### ISSUE TITLE
timestamp folder created in different fingureprintschema folder not in sequence.

### ISSUE THREAD

**Issue by Prakash28raj** [Guidewire/cda-client#4]
I have a table with 2 schemafingerprint directories and there multiple timestamp directories inside it. It was assumed that the timestamp directory with minimum value in 2nd schemafingerprint directory should be greater than the maximum value of the timestamp directory in the 1st schemafingerprint directory, but this is not the case and we are missing data due to it.

As the there are timestamp directories with value less than the max value of the timestamp directory in the 1st schemafingerprint directory . the application picks up data only from the timestamp directories of  2nd schemafingerprint if there value is greater than the max value of the timestamp directory in 1st schemafingerprint .

**Comment by scottrhodes** [comment]
Hi Prakash. This scenario may match a known issue. Please reach out to the
Guidewire Delivery Manager on your project and have them enter a ticket for
this issue. They can contact me via my Guidewire email or Slack as well for
additional information.
I cannot assist outside of official channels however.

Scott Rhodes

**Comment by gw-vsasidharan** [comment]
Closing this issue, since it had to do with CDA, not CDA Client. (And it's already fixed in CDA, FYI).
